my bad
minesa-hub/blehh pull request #13
Opened 2023-05-10 13:34 UTC by Slyrith

my dumbass forgot to update the index while having the format wrong, i need to drink water fr

2023-05-10 13:54 UTC, Neodevils approved these changes
LGTM.

2023-05-10 14:26 UTC, Neodevils requested changes
Renaming file extension would be better for handling.

2023-05-10 14:26 UTC, Neodevils commented on src/index.ts
Exporting as `messageId.js` is fine.

2023-05-10 14:26 UTC, Neodevils commented on src/Functions/Message/messageId.js
Well, the file has to end with `.ts` extension.

2023-05-11 03:55 UTC, Slyrith commented on src/Functions/Message/messageId.js
yep, check commit already fixed it

2023-05-11 05:11 UTC, Neodevils commented on src/Functions/Message/messageId.js
What? It is still messageId.js as file name. 😂

2023-05-11 05:14 UTC, Neodevils commented
![IMG_0900](https://github.com/minesa-hub/blehh/assets/71941576/d692df36-96b5-4b65-9739-ee7d9cde4c79)

2023-05-11 05:45 UTC, Slyrith commented on src/Functions/Message/messageId.js
im trippin

2023-05-11 05:46 UTC, Slyrith commented
im trippin 🥴

2023-05-11 18:39 UTC, merged